export const me = [
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "Fandy Ahmad Januar Pratama (TI-MDI)" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
];

export const other = [
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
  { name: "-" },
];
